/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as AcessoNegadoRouteImport } from './routes/acesso-negado'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventosEventoIdRouteImport } from './routes/eventos.$eventoId'
import { Route as AcompanharProtocoloRouteImport } from './routes/acompanhar.$protocolo'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as ApiPublicAgendamentosRouteImport } from './routes/api/public/agendamentos'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated.admin.usuarios'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated.admin.eventos'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated.admin.auditoria'
import { Route as AuthenticatedAdminEventosNovoRouteImport } from './routes/_authenticated.admin.eventos.novo'
import { Route as AuthenticatedAdminEventosEventoIdRouteImport } from './routes/_authenticated.admin.eventos.$eventoId'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoNegadoRoute = AcessoNegadoRouteImport.update({
  id: '/acesso-negado',
  path: '/acesso-negado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosEventoIdRoute = EventosEventoIdRouteImport.update({
  id: '/$eventoId',
  path: '/$eventoId',
  getParentRoute: () => EventosRoute,
} as any)
const AcompanharProtocoloRoute = AcompanharProtocoloRouteImport.update({
  id: '/acompanhar/$protocolo',
  path: '/acompanhar/$protocolo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicAgendamentosRoute = ApiPublicAgendamentosRouteImport.update({
  id: '/api/public/agendamentos',
  path: '/api/public/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/admin/eventos',
    path: '/admin/eventos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/admin/auditoria',
    path: '/admin/auditoria',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEventosNovoRoute =
  AuthenticatedAdminEventosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedAdminEventosRoute,
  } as any)
const AuthenticatedAdminEventosEventoIdRoute =
  AuthenticatedAdminEventosEventoIdRouteImport.update({
    id: '/$eventoId',
    path: '/$eventoId',
    getParentRoute: () => AuthenticatedAdminEventosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/agendar': typeof AgendarRoute
  '/contato': typeof ContatoRoute
  '/eventos': typeof EventosRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/acompanhar/$protocolo': typeof AcompanharProtocoloRoute
  '/eventos/$eventoId': typeof EventosEventoIdRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRouteWithChildren
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/agendamentos': typeof ApiPublicAgendamentosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/eventos/$eventoId': typeof AuthenticatedAdminEventosEventoIdRoute
  '/admin/eventos/novo': typeof AuthenticatedAdminEventosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/agendar': typeof AgendarRoute
  '/contato': typeof ContatoRoute
  '/eventos': typeof EventosRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/acompanhar/$protocolo': typeof AcompanharProtocoloRoute
  '/eventos/$eventoId': typeof EventosEventoIdRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRouteWithChildren
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/agendamentos': typeof ApiPublicAgendamentosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/eventos/$eventoId': typeof AuthenticatedAdminEventosEventoIdRoute
  '/admin/eventos/novo': typeof AuthenticatedAdminEventosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/acesso-negado': typeof AcessoNegadoRoute
  '/agendar': typeof AgendarRoute
  '/contato': typeof ContatoRoute
  '/eventos': typeof EventosRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/acompanhar/$protocolo': typeof AcompanharProtocoloRoute
  '/eventos/$eventoId': typeof EventosEventoIdRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/eventos': typeof AuthenticatedAdminEventosRouteWithChildren
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/agendamentos': typeof ApiPublicAgendamentosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/eventos/$eventoId': typeof AuthenticatedAdminEventosEventoIdRoute
  '/_authenticated/admin/eventos/novo': typeof AuthenticatedAdminEventosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-negado'
    | '/agendar'
    | '/contato'
    | '/eventos'
    | '/health'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/acompanhar/$protocolo'
    | '/eventos/$eventoId'
    | '/admin/auditoria'
    | '/admin/eventos'
    | '/admin/usuarios'
    | '/api/public/agendamentos'
    | '/admin/'
    | '/admin/eventos/$eventoId'
    | '/admin/eventos/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-negado'
    | '/agendar'
    | '/contato'
    | '/eventos'
    | '/health'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/acompanhar/$protocolo'
    | '/eventos/$eventoId'
    | '/admin/auditoria'
    | '/admin/eventos'
    | '/admin/usuarios'
    | '/api/public/agendamentos'
    | '/admin'
    | '/admin/eventos/$eventoId'
    | '/admin/eventos/novo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acesso-negado'
    | '/agendar'
    | '/contato'
    | '/eventos'
    | '/health'
    | '/login'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/termos'
    | '/acompanhar/$protocolo'
    | '/eventos/$eventoId'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/eventos'
    | '/_authenticated/admin/usuarios'
    | '/api/public/agendamentos'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/eventos/$eventoId'
    | '/_authenticated/admin/eventos/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcessoNegadoRoute: typeof AcessoNegadoRoute
  AgendarRoute: typeof AgendarRoute
  ContatoRoute: typeof ContatoRoute
  EventosRoute: typeof EventosRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TermosRoute: typeof TermosRoute
  AcompanharProtocoloRoute: typeof AcompanharProtocoloRoute
  ApiPublicAgendamentosRoute: typeof ApiPublicAgendamentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-negado': {
      id: '/acesso-negado'
      path: '/acesso-negado'
      fullPath: '/acesso-negado'
      preLoaderRoute: typeof AcessoNegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$eventoId': {
      id: '/eventos/$eventoId'
      path: '/$eventoId'
      fullPath: '/eventos/$eventoId'
      preLoaderRoute: typeof EventosEventoIdRouteImport
      parentRoute: typeof EventosRoute
    }
    '/acompanhar/$protocolo': {
      id: '/acompanhar/$protocolo'
      path: '/acompanhar/$protocolo'
      fullPath: '/acompanhar/$protocolo'
      preLoaderRoute: typeof AcompanharProtocoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/agendamentos': {
      id: '/api/public/agendamentos'
      path: '/api/public/agendamentos'
      fullPath: '/api/public/agendamentos'
      preLoaderRoute: typeof ApiPublicAgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/eventos': {
      id: '/_authenticated/admin/eventos'
      path: '/admin/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/eventos/novo': {
      id: '/_authenticated/admin/eventos/novo'
      path: '/novo'
      fullPath: '/admin/eventos/novo'
      preLoaderRoute: typeof AuthenticatedAdminEventosNovoRouteImport
      parentRoute: typeof AuthenticatedAdminEventosRoute
    }
    '/_authenticated/admin/eventos/$eventoId': {
      id: '/_authenticated/admin/eventos/$eventoId'
      path: '/$eventoId'
      fullPath: '/admin/eventos/$eventoId'
      preLoaderRoute: typeof AuthenticatedAdminEventosEventoIdRouteImport
      parentRoute: typeof AuthenticatedAdminEventosRoute
    }
  }
}

interface AuthenticatedAdminEventosRouteChildren {
  AuthenticatedAdminEventosEventoIdRoute: typeof AuthenticatedAdminEventosEventoIdRoute
  AuthenticatedAdminEventosNovoRoute: typeof AuthenticatedAdminEventosNovoRoute
}

const AuthenticatedAdminEventosRouteChildren: AuthenticatedAdminEventosRouteChildren =
  {
    AuthenticatedAdminEventosEventoIdRoute:
      AuthenticatedAdminEventosEventoIdRoute,
    AuthenticatedAdminEventosNovoRoute: AuthenticatedAdminEventosNovoRoute,
  }

const AuthenticatedAdminEventosRouteWithChildren =
  AuthenticatedAdminEventosRoute._addFileChildren(
    AuthenticatedAdminEventosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRouteWithChildren
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRouteWithChildren,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface EventosRouteChildren {
  EventosEventoIdRoute: typeof EventosEventoIdRoute
}

const EventosRouteChildren: EventosRouteChildren = {
  EventosEventoIdRoute: EventosEventoIdRoute,
}

const EventosRouteWithChildren =
  EventosRoute._addFileChildren(EventosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcessoNegadoRoute: AcessoNegadoRoute,
  AgendarRoute: AgendarRoute,
  ContatoRoute: ContatoRoute,
  EventosRoute: EventosRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TermosRoute: TermosRoute,
  AcompanharProtocoloRoute: AcompanharProtocoloRoute,
  ApiPublicAgendamentosRoute: ApiPublicAgendamentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
